redis:
  host: 8.134.76.254:6379
  password: m1593922
  timeout: 200
  #  最大活动连接数
  max_active: 30
  #  最大闲置连接
  max_idle: 30

httpserverinfo:
  port: 8100
  readtimeout: 10
  writetimeout: 10
  iskeepalive: 1

authwhitelist:
- signature: 4TM2665DWTCBnzpg404
