// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: singal.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebRtcService_Sync_FullMethodName = "/server.WebRtcService/Sync"
)

// WebRtcServiceClient is the client API for WebRtcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebRtcServiceClient interface {
	Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerToServer, ServerToWorker], error)
}

type webRtcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebRtcServiceClient(cc grpc.ClientConnInterface) WebRtcServiceClient {
	return &webRtcServiceClient{cc}
}

func (c *webRtcServiceClient) Sync(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerToServer, ServerToWorker], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WebRtcService_ServiceDesc.Streams[0], WebRtcService_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerToServer, ServerToWorker]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WebRtcService_SyncClient = grpc.BidiStreamingClient[WorkerToServer, ServerToWorker]

// WebRtcServiceServer is the server API for WebRtcService service.
// All implementations must embed UnimplementedWebRtcServiceServer
// for forward compatibility.
type WebRtcServiceServer interface {
	Sync(grpc.BidiStreamingServer[WorkerToServer, ServerToWorker]) error
	mustEmbedUnimplementedWebRtcServiceServer()
}

// UnimplementedWebRtcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebRtcServiceServer struct{}

func (UnimplementedWebRtcServiceServer) Sync(grpc.BidiStreamingServer[WorkerToServer, ServerToWorker]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedWebRtcServiceServer) mustEmbedUnimplementedWebRtcServiceServer() {}
func (UnimplementedWebRtcServiceServer) testEmbeddedByValue()                       {}

// UnsafeWebRtcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebRtcServiceServer will
// result in compilation errors.
type UnsafeWebRtcServiceServer interface {
	mustEmbedUnimplementedWebRtcServiceServer()
}

func RegisterWebRtcServiceServer(s grpc.ServiceRegistrar, srv WebRtcServiceServer) {
	// If the following call panics, it indicates UnimplementedWebRtcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebRtcService_ServiceDesc, srv)
}

func _WebRtcService_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebRtcServiceServer).Sync(&grpc.GenericServerStream[WorkerToServer, ServerToWorker]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WebRtcService_SyncServer = grpc.BidiStreamingServer[WorkerToServer, ServerToWorker]

// WebRtcService_ServiceDesc is the grpc.ServiceDesc for WebRtcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebRtcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server.WebRtcService",
	HandlerType: (*WebRtcServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _WebRtcService_Sync_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "singal.proto",
}
