// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: sfu.proto

package sfu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNKNOWN MessageType = 0
	// client request
	MessageType_REGISTER           MessageType = 1
	MessageType_KEEPALIVE          MessageType = 2
	MessageType_FLOW_REPORT        MessageType = 3
	MessageType_AUDIO_LEVEL_REPORT MessageType = 4
	// server request
	MessageType_CREATE_ROUTER  MessageType = 101
	MessageType_PRODUCE_UPDATE MessageType = 102
	MessageType_CONSUME_UPDATE MessageType = 103
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "REGISTER",
		2:   "KEEPALIVE",
		3:   "FLOW_REPORT",
		4:   "AUDIO_LEVEL_REPORT",
		101: "CREATE_ROUTER",
		102: "PRODUCE_UPDATE",
		103: "CONSUME_UPDATE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":            0,
		"REGISTER":           1,
		"KEEPALIVE":          2,
		"FLOW_REPORT":        3,
		"AUDIO_LEVEL_REPORT": 4,
		"CREATE_ROUTER":      101,
		"PRODUCE_UPDATE":     102,
		"CONSUME_UPDATE":     103,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_sfu_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_sfu_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_sfu_proto_rawDescGZIP(), []int{0}
}

type ProduceState int32

const (
	ProduceState_CREATE ProduceState = 0
	ProduceState_PAUSE  ProduceState = 1
	ProduceState_RESUME ProduceState = 2
	ProduceState_CLOSE  ProduceState = 3
)

// Enum value maps for ProduceState.
var (
	ProduceState_name = map[int32]string{
		0: "CREATE",
		1: "PAUSE",
		2: "RESUME",
		3: "CLOSE",
	}
	ProduceState_value = map[string]int32{
		"CREATE": 0,
		"PAUSE":  1,
		"RESUME": 2,
		"CLOSE":  3,
	}
)

func (x ProduceState) Enum() *ProduceState {
	p := new(ProduceState)
	*p = x
	return p
}

func (x ProduceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProduceState) Descriptor() protoreflect.EnumDescriptor {
	return file_sfu_proto_enumTypes[1].Descriptor()
}

func (ProduceState) Type() protoreflect.EnumType {
	return &file_sfu_proto_enumTypes[1]
}

func (x ProduceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProduceState.Descriptor instead.
func (ProduceState) EnumDescriptor() ([]byte, []int) {
	return file_sfu_proto_rawDescGZIP(), []int{1}
}

type SfuMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=sfu.MessageType" json:"type,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// message content
	//
	// Types that are valid to be assigned to Content:
	//
	//	*SfuMessage_RegisterRequest
	//	*SfuMessage_KeepaliveRequest
	//	*SfuMessage_AudioLevelRequest
	//	*SfuMessage_FlowReportRequest
	//	*SfuMessage_CreateRouteRequest
	//	*SfuMessage_ProduceStateRequest
	//	*SfuMessage_ConsumeStateRequest
	//	*SfuMessage_TextMessage
	Content       isSfuMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SfuMessage) Reset() {
	*x = SfuMessage{}
	mi := &file_sfu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SfuMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SfuMessage) ProtoMessage() {}

func (x *SfuMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SfuMessage.ProtoReflect.Descriptor instead.
func (*SfuMessage) Descriptor() ([]byte, []int) {
	return file_sfu_proto_rawDescGZIP(), []int{0}
}

func (x *SfuMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *SfuMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SfuMessage) GetContent() isSfuMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *SfuMessage) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Content.(*SfuMessage_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *SfuMessage) GetKeepaliveRequest() *KeepaliveRequest {
	if x != nil {
		if x, ok := x.Content.(*SfuMessage_KeepaliveRequest); ok {
			return x.KeepaliveRequest
		}
	}
	return nil
}

func (x *SfuMessage) GetAudioLevelRequest() *AudioLevelRequest {
	if x != nil {
		if x, ok := x.Content.(*SfuMessage_AudioLevelRequest); ok {
			return x.AudioLevelRequest
		}
	}
	return nil
}

func (x *SfuMessage) GetFlowReportRequest() *FlowReportRequest {
	if x != nil {
		if x, ok := x.Content.(*SfuMessage_FlowReportRequest); ok {
			return x.FlowReportRequest
		}
	}
	return nil
}

func (x *SfuMessage) GetCreateRouteRequest() *CreateRouterRequest {
	if x != nil {
		if x, ok := x.Content.(*SfuMessage_CreateRouteRequest); ok {
			return x.CreateRouteRequest
		}
	}
	return nil
}

func (x *SfuMessage) GetProduceStateRequest() *ProduceStateRequest {
	if x != nil {
		if x, ok := x.Content.(*SfuMessage_ProduceStateRequest); ok {
			return x.ProduceStateRequest
		}
	}
	return nil
}

func (x *SfuMessage) GetConsumeStateRequest() *ConsumeStateRequest {
	if x != nil {
		if x, ok := x.Content.(*SfuMessage_ConsumeStateRequest); ok {
			return x.ConsumeStateRequest
		}
	}
	return nil
}

func (x *SfuMessage) GetTextMessage() string {
	if x != nil {
		if x, ok := x.Content.(*SfuMessage_TextMessage); ok {
			return x.TextMessage
		}
	}
	return ""
}

type isSfuMessage_Content interface {
	isSfuMessage_Content()
}

type SfuMessage_RegisterRequest struct {
	RegisterRequest *RegisterRequest `protobuf:"bytes,10,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type SfuMessage_KeepaliveRequest struct {
	KeepaliveRequest *KeepaliveRequest `protobuf:"bytes,11,opt,name=keepalive_request,json=keepaliveRequest,proto3,oneof"`
}

type SfuMessage_AudioLevelRequest struct {
	AudioLevelRequest *AudioLevelRequest `protobuf:"bytes,12,opt,name=audio_level_request,json=audioLevelRequest,proto3,oneof"`
}

type SfuMessage_FlowReportRequest struct {
	FlowReportRequest *FlowReportRequest `protobuf:"bytes,13,opt,name=flow_report_request,json=flowReportRequest,proto3,oneof"`
}

type SfuMessage_CreateRouteRequest struct {
	CreateRouteRequest *CreateRouterRequest `protobuf:"bytes,14,opt,name=create_route_request,json=createRouteRequest,proto3,oneof"`
}

type SfuMessage_ProduceStateRequest struct {
	ProduceStateRequest *ProduceStateRequest `protobuf:"bytes,15,opt,name=produce_state_request,json=produceStateRequest,proto3,oneof"`
}

type SfuMessage_ConsumeStateRequest struct {
	ConsumeStateRequest *ConsumeStateRequest `protobuf:"bytes,16,opt,name=consume_state_request,json=consumeStateRequest,proto3,oneof"`
}

type SfuMessage_TextMessage struct {
	TextMessage string `protobuf:"bytes,17,opt,name=text_message,json=textMessage,proto3,oneof"`
}

func (*SfuMessage_RegisterRequest) isSfuMessage_Content() {}

func (*SfuMessage_KeepaliveRequest) isSfuMessage_Content() {}

func (*SfuMessage_AudioLevelRequest) isSfuMessage_Content() {}

func (*SfuMessage_FlowReportRequest) isSfuMessage_Content() {}

func (*SfuMessage_CreateRouteRequest) isSfuMessage_Content() {}

func (*SfuMessage_ProduceStateRequest) isSfuMessage_Content() {}

func (*SfuMessage_ConsumeStateRequest) isSfuMessage_Content() {}

func (*SfuMessage_TextMessage) isSfuMessage_Content() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_sfu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_sfu_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type KeepaliveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepaliveRequest) Reset() {
	*x = KeepaliveRequest{}
	mi := &file_sfu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepaliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveRequest) ProtoMessage() {}

func (x *KeepaliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveRequest.ProtoReflect.Descriptor instead.
func (*KeepaliveRequest) Descriptor() ([]byte, []int) {
	return file_sfu_proto_rawDescGZIP(), []int{2}
}

func (x *KeepaliveRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type FlowReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowReportRequest) Reset() {
	*x = FlowReportRequest{}
	mi := &file_sfu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowReportRequest) ProtoMessage() {}

func (x *FlowReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowReportRequest.ProtoReflect.Descriptor instead.
func (*FlowReportRequest) Descriptor() ([]byte, []int) {
	return file_sfu_proto_rawDescGZIP(), []int{3}
}

func (x *FlowReportRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type AudioLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioLevelRequest) Reset() {
	*x = AudioLevelRequest{}
	mi := &file_sfu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioLevelRequest) ProtoMessage() {}

func (x *AudioLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioLevelRequest.ProtoReflect.Descriptor instead.
func (*AudioLevelRequest) Descriptor() ([]byte, []int) {
	return file_sfu_proto_rawDescGZIP(), []int{4}
}

func (x *AudioLevelRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type CreateRouterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouterRequest) Reset() {
	*x = CreateRouterRequest{}
	mi := &file_sfu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouterRequest) ProtoMessage() {}

func (x *CreateRouterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouterRequest.ProtoReflect.Descriptor instead.
func (*CreateRouterRequest) Descriptor() ([]byte, []int) {
	return file_sfu_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRouterRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ProduceStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceStateRequest) Reset() {
	*x = ProduceStateRequest{}
	mi := &file_sfu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceStateRequest) ProtoMessage() {}

func (x *ProduceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceStateRequest.ProtoReflect.Descriptor instead.
func (*ProduceStateRequest) Descriptor() ([]byte, []int) {
	return file_sfu_proto_rawDescGZIP(), []int{6}
}

func (x *ProduceStateRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type ConsumeStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeStateRequest) Reset() {
	*x = ConsumeStateRequest{}
	mi := &file_sfu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeStateRequest) ProtoMessage() {}

func (x *ConsumeStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sfu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeStateRequest.ProtoReflect.Descriptor instead.
func (*ConsumeStateRequest) Descriptor() ([]byte, []int) {
	return file_sfu_proto_rawDescGZIP(), []int{7}
}

func (x *ConsumeStateRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

var File_sfu_proto protoreflect.FileDescriptor

const file_sfu_proto_rawDesc = "" +
	"\n" +
	"\tsfu.proto\x12\x03sfu\"\x8b\x05\n" +
	"\n" +
	"SfuMessage\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.sfu.MessageTypeR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12A\n" +
	"\x10register_request\x18\n" +
	" \x01(\v2\x14.sfu.RegisterRequestH\x00R\x0fregisterRequest\x12D\n" +
	"\x11keepalive_request\x18\v \x01(\v2\x15.sfu.KeepaliveRequestH\x00R\x10keepaliveRequest\x12H\n" +
	"\x13audio_level_request\x18\f \x01(\v2\x16.sfu.AudioLevelRequestH\x00R\x11audioLevelRequest\x12H\n" +
	"\x13flow_report_request\x18\r \x01(\v2\x16.sfu.FlowReportRequestH\x00R\x11flowReportRequest\x12L\n" +
	"\x14create_route_request\x18\x0e \x01(\v2\x18.sfu.CreateRouterRequestH\x00R\x12createRouteRequest\x12N\n" +
	"\x15produce_state_request\x18\x0f \x01(\v2\x18.sfu.ProduceStateRequestH\x00R\x13produceStateRequest\x12N\n" +
	"\x15consume_state_request\x18\x10 \x01(\v2\x18.sfu.ConsumeStateRequestH\x00R\x13consumeStateRequest\x12#\n" +
	"\ftext_message\x18\x11 \x01(\tH\x00R\vtextMessageB\t\n" +
	"\acontent\".\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"/\n" +
	"\x10KeepaliveRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"0\n" +
	"\x11FlowReportRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"0\n" +
	"\x11AudioLevelRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"2\n" +
	"\x13CreateRouterRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"2\n" +
	"\x13ProduceStateRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"2\n" +
	"\x13ConsumeStateRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId*\x9b\x01\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bREGISTER\x10\x01\x12\r\n" +
	"\tKEEPALIVE\x10\x02\x12\x0f\n" +
	"\vFLOW_REPORT\x10\x03\x12\x16\n" +
	"\x12AUDIO_LEVEL_REPORT\x10\x04\x12\x11\n" +
	"\rCREATE_ROUTER\x10e\x12\x12\n" +
	"\x0ePRODUCE_UPDATE\x10f\x12\x12\n" +
	"\x0eCONSUME_UPDATE\x10g*<\n" +
	"\fProduceState\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\n" +
	"\n" +
	"\x06RESUME\x10\x02\x12\t\n" +
	"\x05CLOSE\x10\x032@\n" +
	"\n" +
	"SfuService\x122\n" +
	"\n" +
	"SfuSession\x12\x0f.sfu.SfuMessage\x1a\x0f.sfu.SfuMessage(\x010\x01B\aZ\x05./sfub\x06proto3"

var (
	file_sfu_proto_rawDescOnce sync.Once
	file_sfu_proto_rawDescData []byte
)

func file_sfu_proto_rawDescGZIP() []byte {
	file_sfu_proto_rawDescOnce.Do(func() {
		file_sfu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sfu_proto_rawDesc), len(file_sfu_proto_rawDesc)))
	})
	return file_sfu_proto_rawDescData
}

var file_sfu_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_sfu_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sfu_proto_goTypes = []any{
	(MessageType)(0),            // 0: sfu.MessageType
	(ProduceState)(0),           // 1: sfu.ProduceState
	(*SfuMessage)(nil),          // 2: sfu.SfuMessage
	(*RegisterRequest)(nil),     // 3: sfu.RegisterRequest
	(*KeepaliveRequest)(nil),    // 4: sfu.KeepaliveRequest
	(*FlowReportRequest)(nil),   // 5: sfu.FlowReportRequest
	(*AudioLevelRequest)(nil),   // 6: sfu.AudioLevelRequest
	(*CreateRouterRequest)(nil), // 7: sfu.CreateRouterRequest
	(*ProduceStateRequest)(nil), // 8: sfu.ProduceStateRequest
	(*ConsumeStateRequest)(nil), // 9: sfu.ConsumeStateRequest
}
var file_sfu_proto_depIdxs = []int32{
	0, // 0: sfu.SfuMessage.type:type_name -> sfu.MessageType
	3, // 1: sfu.SfuMessage.register_request:type_name -> sfu.RegisterRequest
	4, // 2: sfu.SfuMessage.keepalive_request:type_name -> sfu.KeepaliveRequest
	6, // 3: sfu.SfuMessage.audio_level_request:type_name -> sfu.AudioLevelRequest
	5, // 4: sfu.SfuMessage.flow_report_request:type_name -> sfu.FlowReportRequest
	7, // 5: sfu.SfuMessage.create_route_request:type_name -> sfu.CreateRouterRequest
	8, // 6: sfu.SfuMessage.produce_state_request:type_name -> sfu.ProduceStateRequest
	9, // 7: sfu.SfuMessage.consume_state_request:type_name -> sfu.ConsumeStateRequest
	2, // 8: sfu.SfuService.SfuSession:input_type -> sfu.SfuMessage
	2, // 9: sfu.SfuService.SfuSession:output_type -> sfu.SfuMessage
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_sfu_proto_init() }
func file_sfu_proto_init() {
	if File_sfu_proto != nil {
		return
	}
	file_sfu_proto_msgTypes[0].OneofWrappers = []any{
		(*SfuMessage_RegisterRequest)(nil),
		(*SfuMessage_KeepaliveRequest)(nil),
		(*SfuMessage_AudioLevelRequest)(nil),
		(*SfuMessage_FlowReportRequest)(nil),
		(*SfuMessage_CreateRouteRequest)(nil),
		(*SfuMessage_ProduceStateRequest)(nil),
		(*SfuMessage_ConsumeStateRequest)(nil),
		(*SfuMessage_TextMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sfu_proto_rawDesc), len(file_sfu_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sfu_proto_goTypes,
		DependencyIndexes: file_sfu_proto_depIdxs,
		EnumInfos:         file_sfu_proto_enumTypes,
		MessageInfos:      file_sfu_proto_msgTypes,
	}.Build()
	File_sfu_proto = out.File
	file_sfu_proto_goTypes = nil
	file_sfu_proto_depIdxs = nil
}
