// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: sfu.proto

package sfu

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SfuService_SfuSession_FullMethodName = "/sfu.SfuService/SfuSession"
)

// SfuServiceClient is the client API for SfuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SfuServiceClient interface {
	SfuSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SfuMessage, SfuMessage], error)
}

type sfuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSfuServiceClient(cc grpc.ClientConnInterface) SfuServiceClient {
	return &sfuServiceClient{cc}
}

func (c *sfuServiceClient) SfuSession(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SfuMessage, SfuMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SfuService_ServiceDesc.Streams[0], SfuService_SfuSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SfuMessage, SfuMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SfuService_SfuSessionClient = grpc.BidiStreamingClient[SfuMessage, SfuMessage]

// SfuServiceServer is the server API for SfuService service.
// All implementations must embed UnimplementedSfuServiceServer
// for forward compatibility.
type SfuServiceServer interface {
	SfuSession(grpc.BidiStreamingServer[SfuMessage, SfuMessage]) error
	mustEmbedUnimplementedSfuServiceServer()
}

// UnimplementedSfuServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSfuServiceServer struct{}

func (UnimplementedSfuServiceServer) SfuSession(grpc.BidiStreamingServer[SfuMessage, SfuMessage]) error {
	return status.Error(codes.Unimplemented, "method SfuSession not implemented")
}
func (UnimplementedSfuServiceServer) mustEmbedUnimplementedSfuServiceServer() {}
func (UnimplementedSfuServiceServer) testEmbeddedByValue()                    {}

// UnsafeSfuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SfuServiceServer will
// result in compilation errors.
type UnsafeSfuServiceServer interface {
	mustEmbedUnimplementedSfuServiceServer()
}

func RegisterSfuServiceServer(s grpc.ServiceRegistrar, srv SfuServiceServer) {
	// If the following call panics, it indicates UnimplementedSfuServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SfuService_ServiceDesc, srv)
}

func _SfuService_SfuSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SfuServiceServer).SfuSession(&grpc.GenericServerStream[SfuMessage, SfuMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SfuService_SfuSessionServer = grpc.BidiStreamingServer[SfuMessage, SfuMessage]

// SfuService_ServiceDesc is the grpc.ServiceDesc for SfuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SfuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sfu.SfuService",
	HandlerType: (*SfuServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SfuSession",
			Handler:       _SfuService_SfuSession_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sfu.proto",
}
