// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: singal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportDirection int32

const (
	TransportDirection_DIRECTION_AUTO TransportDirection = 0
	TransportDirection_DIRECTION_SEND TransportDirection = 1
	TransportDirection_DIRECTION_RECV TransportDirection = 2
	TransportDirection_DIRECTION_BOTH TransportDirection = 3
)

// Enum value maps for TransportDirection.
var (
	TransportDirection_name = map[int32]string{
		0: "DIRECTION_AUTO",
		1: "DIRECTION_SEND",
		2: "DIRECTION_RECV",
		3: "DIRECTION_BOTH",
	}
	TransportDirection_value = map[string]int32{
		"DIRECTION_AUTO": 0,
		"DIRECTION_SEND": 1,
		"DIRECTION_RECV": 2,
		"DIRECTION_BOTH": 3,
	}
)

func (x TransportDirection) Enum() *TransportDirection {
	p := new(TransportDirection)
	*p = x
	return p
}

func (x TransportDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_singal_proto_enumTypes[0].Descriptor()
}

func (TransportDirection) Type() protoreflect.EnumType {
	return &file_singal_proto_enumTypes[0]
}

func (x TransportDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportDirection.Descriptor instead.
func (TransportDirection) EnumDescriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{0}
}

type MediaKind int32

const (
	MediaKind_MEDIA_KIND_AUDIO MediaKind = 0
	MediaKind_MEDIA_KIND_VIDEO MediaKind = 1
)

// Enum value maps for MediaKind.
var (
	MediaKind_name = map[int32]string{
		0: "MEDIA_KIND_AUDIO",
		1: "MEDIA_KIND_VIDEO",
	}
	MediaKind_value = map[string]int32{
		"MEDIA_KIND_AUDIO": 0,
		"MEDIA_KIND_VIDEO": 1,
	}
)

func (x MediaKind) Enum() *MediaKind {
	p := new(MediaKind)
	*p = x
	return p
}

func (x MediaKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaKind) Descriptor() protoreflect.EnumDescriptor {
	return file_singal_proto_enumTypes[1].Descriptor()
}

func (MediaKind) Type() protoreflect.EnumType {
	return &file_singal_proto_enumTypes[1]
}

func (x MediaKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaKind.Descriptor instead.
func (MediaKind) EnumDescriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{1}
}

type ListenInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Protocol         string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Ip               string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port             uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	AnnouncedAddress string                 `protobuf:"bytes,4,opt,name=announced_address,json=announcedAddress,proto3" json:"announced_address,omitempty"`
	AnnouncedIp      string                 `protobuf:"bytes,5,opt,name=announced_ip,json=announcedIp,proto3" json:"announced_ip,omitempty"`
	AnnouncedPort    uint32                 `protobuf:"varint,6,opt,name=announced_port,json=announcedPort,proto3" json:"announced_port,omitempty"`
	Tcp              bool                   `protobuf:"varint,7,opt,name=tcp,proto3" json:"tcp,omitempty"`
	Ipv6Only         bool                   `protobuf:"varint,8,opt,name=ipv6Only,proto3" json:"ipv6Only,omitempty"`
	UdpReusePort     bool                   `protobuf:"varint,9,opt,name=udpReusePort,proto3" json:"udpReusePort,omitempty"`
	RecvBufferSize   uint32                 `protobuf:"varint,10,opt,name=recv_buffer_size,json=recvBufferSize,proto3" json:"recv_buffer_size,omitempty"`
	SendBufferSize   uint32                 `protobuf:"varint,11,opt,name=send_buffer_size,json=sendBufferSize,proto3" json:"send_buffer_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListenInfo) Reset() {
	*x = ListenInfo{}
	mi := &file_singal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenInfo) ProtoMessage() {}

func (x *ListenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenInfo.ProtoReflect.Descriptor instead.
func (*ListenInfo) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{0}
}

func (x *ListenInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListenInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ListenInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ListenInfo) GetAnnouncedAddress() string {
	if x != nil {
		return x.AnnouncedAddress
	}
	return ""
}

func (x *ListenInfo) GetAnnouncedIp() string {
	if x != nil {
		return x.AnnouncedIp
	}
	return ""
}

func (x *ListenInfo) GetAnnouncedPort() uint32 {
	if x != nil {
		return x.AnnouncedPort
	}
	return 0
}

func (x *ListenInfo) GetTcp() bool {
	if x != nil {
		return x.Tcp
	}
	return false
}

func (x *ListenInfo) GetIpv6Only() bool {
	if x != nil {
		return x.Ipv6Only
	}
	return false
}

func (x *ListenInfo) GetUdpReusePort() bool {
	if x != nil {
		return x.UdpReusePort
	}
	return false
}

func (x *ListenInfo) GetRecvBufferSize() uint32 {
	if x != nil {
		return x.RecvBufferSize
	}
	return 0
}

func (x *ListenInfo) GetSendBufferSize() uint32 {
	if x != nil {
		return x.SendBufferSize
	}
	return 0
}

type CreateRouterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Info          *ListenInfo            `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouterRequest) Reset() {
	*x = CreateRouterRequest{}
	mi := &file_singal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouterRequest) ProtoMessage() {}

func (x *CreateRouterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouterRequest.ProtoReflect.Descriptor instead.
func (*CreateRouterRequest) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRouterRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CreateRouterRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateRouterRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateRouterRequest) GetInfo() *ListenInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type CreateRouterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorDetail   string                 `protobuf:"bytes,3,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouterResponse) Reset() {
	*x = CreateRouterResponse{}
	mi := &file_singal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouterResponse) ProtoMessage() {}

func (x *CreateRouterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouterResponse.ProtoReflect.Descriptor instead.
func (*CreateRouterResponse) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{2}
}

func (x *CreateRouterResponse) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *CreateRouterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRouterResponse) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

type DtlsFingerprint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DtlsFingerprint) Reset() {
	*x = DtlsFingerprint{}
	mi := &file_singal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DtlsFingerprint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DtlsFingerprint) ProtoMessage() {}

func (x *DtlsFingerprint) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DtlsFingerprint.ProtoReflect.Descriptor instead.
func (*DtlsFingerprint) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{3}
}

func (x *DtlsFingerprint) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *DtlsFingerprint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IceCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foundation    string                 `protobuf:"bytes,1,opt,name=foundation,proto3" json:"foundation,omitempty"`
	Priority      uint32                 `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint32                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	TcpType       string                 `protobuf:"bytes,7,opt,name=tcp_type,json=tcpType,proto3" json:"tcp_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IceCandidate) Reset() {
	*x = IceCandidate{}
	mi := &file_singal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IceCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IceCandidate) ProtoMessage() {}

func (x *IceCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IceCandidate.ProtoReflect.Descriptor instead.
func (*IceCandidate) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{4}
}

func (x *IceCandidate) GetFoundation() string {
	if x != nil {
		return x.Foundation
	}
	return ""
}

func (x *IceCandidate) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *IceCandidate) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *IceCandidate) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *IceCandidate) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *IceCandidate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IceCandidate) GetTcpType() string {
	if x != nil {
		return x.TcpType
	}
	return ""
}

type CreateTransportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	RouterId      string                 `protobuf:"bytes,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	TransportId   string                 `protobuf:"bytes,3,opt,name=transport_id,json=transportId,proto3" json:"transport_id,omitempty"`
	Direction     TransportDirection     `protobuf:"varint,4,opt,name=direction,proto3,enum=server.TransportDirection" json:"direction,omitempty"`
	EnableUdp     bool                   `protobuf:"varint,5,opt,name=enable_udp,json=enableUdp,proto3" json:"enable_udp,omitempty"`
	EnableTcp     bool                   `protobuf:"varint,6,opt,name=enable_tcp,json=enableTcp,proto3" json:"enable_tcp,omitempty"`
	PreferUdp     bool                   `protobuf:"varint,7,opt,name=prefer_udp,json=preferUdp,proto3" json:"prefer_udp,omitempty"`
	PreferTcp     bool                   `protobuf:"varint,8,opt,name=prefer_tcp,json=preferTcp,proto3" json:"prefer_tcp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransportRequest) Reset() {
	*x = CreateTransportRequest{}
	mi := &file_singal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransportRequest) ProtoMessage() {}

func (x *CreateTransportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransportRequest.ProtoReflect.Descriptor instead.
func (*CreateTransportRequest) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTransportRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *CreateTransportRequest) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *CreateTransportRequest) GetTransportId() string {
	if x != nil {
		return x.TransportId
	}
	return ""
}

func (x *CreateTransportRequest) GetDirection() TransportDirection {
	if x != nil {
		return x.Direction
	}
	return TransportDirection_DIRECTION_AUTO
}

func (x *CreateTransportRequest) GetEnableUdp() bool {
	if x != nil {
		return x.EnableUdp
	}
	return false
}

func (x *CreateTransportRequest) GetEnableTcp() bool {
	if x != nil {
		return x.EnableTcp
	}
	return false
}

func (x *CreateTransportRequest) GetPreferUdp() bool {
	if x != nil {
		return x.PreferUdp
	}
	return false
}

func (x *CreateTransportRequest) GetPreferTcp() bool {
	if x != nil {
		return x.PreferTcp
	}
	return false
}

type CreateTransportResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransportId      string                 `protobuf:"bytes,1,opt,name=transport_id,json=transportId,proto3" json:"transport_id,omitempty"`
	IceUfrag         string                 `protobuf:"bytes,2,opt,name=ice_ufrag,json=iceUfrag,proto3" json:"ice_ufrag,omitempty"`
	IcePwd           string                 `protobuf:"bytes,3,opt,name=ice_pwd,json=icePwd,proto3" json:"ice_pwd,omitempty"`
	IceCandidates    []*IceCandidate        `protobuf:"bytes,4,rep,name=ice_candidates,json=iceCandidates,proto3" json:"ice_candidates,omitempty"`
	DtlsFingerprints []*DtlsFingerprint     `protobuf:"bytes,5,rep,name=dtls_fingerprints,json=dtlsFingerprints,proto3" json:"dtls_fingerprints,omitempty"`
	DtlsRole         string                 `protobuf:"bytes,6,opt,name=dtls_role,json=dtlsRole,proto3" json:"dtls_role,omitempty"`
	Success          bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	ErrorDetail      string                 `protobuf:"bytes,8,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTransportResponse) Reset() {
	*x = CreateTransportResponse{}
	mi := &file_singal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransportResponse) ProtoMessage() {}

func (x *CreateTransportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransportResponse.ProtoReflect.Descriptor instead.
func (*CreateTransportResponse) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTransportResponse) GetTransportId() string {
	if x != nil {
		return x.TransportId
	}
	return ""
}

func (x *CreateTransportResponse) GetIceUfrag() string {
	if x != nil {
		return x.IceUfrag
	}
	return ""
}

func (x *CreateTransportResponse) GetIcePwd() string {
	if x != nil {
		return x.IcePwd
	}
	return ""
}

func (x *CreateTransportResponse) GetIceCandidates() []*IceCandidate {
	if x != nil {
		return x.IceCandidates
	}
	return nil
}

func (x *CreateTransportResponse) GetDtlsFingerprints() []*DtlsFingerprint {
	if x != nil {
		return x.DtlsFingerprints
	}
	return nil
}

func (x *CreateTransportResponse) GetDtlsRole() string {
	if x != nil {
		return x.DtlsRole
	}
	return ""
}

func (x *CreateTransportResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateTransportResponse) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransportId   string                 `protobuf:"bytes,1,opt,name=transport_id,json=transportId,proto3" json:"transport_id,omitempty"`
	Kind          MediaKind              `protobuf:"varint,2,opt,name=kind,proto3,enum=server.MediaKind" json:"kind,omitempty"`
	AppData       string                 `protobuf:"bytes,3,opt,name=app_data,json=appData,proto3" json:"app_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_singal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{7}
}

func (x *ProduceRequest) GetTransportId() string {
	if x != nil {
		return x.TransportId
	}
	return ""
}

func (x *ProduceRequest) GetKind() MediaKind {
	if x != nil {
		return x.Kind
	}
	return MediaKind_MEDIA_KIND_AUDIO
}

func (x *ProduceRequest) GetAppData() string {
	if x != nil {
		return x.AppData
	}
	return ""
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProducerId    string                 `protobuf:"bytes,1,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorDetail   string                 `protobuf:"bytes,3,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_singal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{8}
}

func (x *ProduceResponse) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *ProduceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProduceResponse) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransportId   string                 `protobuf:"bytes,1,opt,name=transport_id,json=transportId,proto3" json:"transport_id,omitempty"`
	ProducerId    string                 `protobuf:"bytes,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_singal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{9}
}

func (x *ConsumeRequest) GetTransportId() string {
	if x != nil {
		return x.TransportId
	}
	return ""
}

func (x *ConsumeRequest) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerId    string                 `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	ProducerId    string                 `protobuf:"bytes,2,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	Kind          MediaKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=server.MediaKind" json:"kind,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorDetail   string                 `protobuf:"bytes,5,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_singal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{10}
}

func (x *ConsumeResponse) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumeResponse) GetProducerId() string {
	if x != nil {
		return x.ProducerId
	}
	return ""
}

func (x *ConsumeResponse) GetKind() MediaKind {
	if x != nil {
		return x.Kind
	}
	return MediaKind_MEDIA_KIND_AUDIO
}

func (x *ConsumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeResponse) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

type WorkerToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	SeqId uint64                 `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkerToServer_CreateRouterRes
	//	*WorkerToServer_CreateTransportRes
	//	*WorkerToServer_ProduceRes
	//	*WorkerToServer_ConsumerRes
	//	*WorkerToServer_StatsPush
	Payload       isWorkerToServer_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerToServer) Reset() {
	*x = WorkerToServer{}
	mi := &file_singal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerToServer) ProtoMessage() {}

func (x *WorkerToServer) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerToServer.ProtoReflect.Descriptor instead.
func (*WorkerToServer) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{11}
}

func (x *WorkerToServer) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *WorkerToServer) GetPayload() isWorkerToServer_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkerToServer) GetCreateRouterRes() *CreateRouterResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerToServer_CreateRouterRes); ok {
			return x.CreateRouterRes
		}
	}
	return nil
}

func (x *WorkerToServer) GetCreateTransportRes() *CreateTransportResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerToServer_CreateTransportRes); ok {
			return x.CreateTransportRes
		}
	}
	return nil
}

func (x *WorkerToServer) GetProduceRes() *ProduceResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerToServer_ProduceRes); ok {
			return x.ProduceRes
		}
	}
	return nil
}

func (x *WorkerToServer) GetConsumerRes() *ConsumeResponse {
	if x != nil {
		if x, ok := x.Payload.(*WorkerToServer_ConsumerRes); ok {
			return x.ConsumerRes
		}
	}
	return nil
}

func (x *WorkerToServer) GetStatsPush() string {
	if x != nil {
		if x, ok := x.Payload.(*WorkerToServer_StatsPush); ok {
			return x.StatsPush
		}
	}
	return ""
}

type isWorkerToServer_Payload interface {
	isWorkerToServer_Payload()
}

type WorkerToServer_CreateRouterRes struct {
	CreateRouterRes *CreateRouterResponse `protobuf:"bytes,2,opt,name=create_router_res,json=createRouterRes,proto3,oneof"`
}

type WorkerToServer_CreateTransportRes struct {
	CreateTransportRes *CreateTransportResponse `protobuf:"bytes,3,opt,name=create_transport_res,json=createTransportRes,proto3,oneof"`
}

type WorkerToServer_ProduceRes struct {
	ProduceRes *ProduceResponse `protobuf:"bytes,4,opt,name=produce_res,json=produceRes,proto3,oneof"`
}

type WorkerToServer_ConsumerRes struct {
	ConsumerRes *ConsumeResponse `protobuf:"bytes,5,opt,name=consumer_res,json=consumerRes,proto3,oneof"`
}

type WorkerToServer_StatsPush struct {
	StatsPush string `protobuf:"bytes,6,opt,name=stats_push,json=statsPush,proto3,oneof"`
}

func (*WorkerToServer_CreateRouterRes) isWorkerToServer_Payload() {}

func (*WorkerToServer_CreateTransportRes) isWorkerToServer_Payload() {}

func (*WorkerToServer_ProduceRes) isWorkerToServer_Payload() {}

func (*WorkerToServer_ConsumerRes) isWorkerToServer_Payload() {}

func (*WorkerToServer_StatsPush) isWorkerToServer_Payload() {}

type ServerToWorker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	SeqId uint64                 `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerToWorker_CreateRouterReq
	//	*ServerToWorker_CreateTransportReq
	//	*ServerToWorker_ProduceReq
	//	*ServerToWorker_ConsumerReq
	//	*ServerToWorker_GlobalNotification
	Payload       isServerToWorker_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToWorker) Reset() {
	*x = ServerToWorker{}
	mi := &file_singal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToWorker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToWorker) ProtoMessage() {}

func (x *ServerToWorker) ProtoReflect() protoreflect.Message {
	mi := &file_singal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToWorker.ProtoReflect.Descriptor instead.
func (*ServerToWorker) Descriptor() ([]byte, []int) {
	return file_singal_proto_rawDescGZIP(), []int{12}
}

func (x *ServerToWorker) GetSeqId() uint64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *ServerToWorker) GetPayload() isServerToWorker_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerToWorker) GetCreateRouterReq() *CreateRouterRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerToWorker_CreateRouterReq); ok {
			return x.CreateRouterReq
		}
	}
	return nil
}

func (x *ServerToWorker) GetCreateTransportReq() *CreateTransportRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerToWorker_CreateTransportReq); ok {
			return x.CreateTransportReq
		}
	}
	return nil
}

func (x *ServerToWorker) GetProduceReq() *ProduceRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerToWorker_ProduceReq); ok {
			return x.ProduceReq
		}
	}
	return nil
}

func (x *ServerToWorker) GetConsumerReq() *ConsumeRequest {
	if x != nil {
		if x, ok := x.Payload.(*ServerToWorker_ConsumerReq); ok {
			return x.ConsumerReq
		}
	}
	return nil
}

func (x *ServerToWorker) GetGlobalNotification() string {
	if x != nil {
		if x, ok := x.Payload.(*ServerToWorker_GlobalNotification); ok {
			return x.GlobalNotification
		}
	}
	return ""
}

type isServerToWorker_Payload interface {
	isServerToWorker_Payload()
}

type ServerToWorker_CreateRouterReq struct {
	CreateRouterReq *CreateRouterRequest `protobuf:"bytes,2,opt,name=create_router_req,json=createRouterReq,proto3,oneof"`
}

type ServerToWorker_CreateTransportReq struct {
	CreateTransportReq *CreateTransportRequest `protobuf:"bytes,3,opt,name=create_transport_req,json=createTransportReq,proto3,oneof"`
}

type ServerToWorker_ProduceReq struct {
	ProduceReq *ProduceRequest `protobuf:"bytes,4,opt,name=produce_req,json=produceReq,proto3,oneof"`
}

type ServerToWorker_ConsumerReq struct {
	ConsumerReq *ConsumeRequest `protobuf:"bytes,5,opt,name=consumer_req,json=consumerReq,proto3,oneof"`
}

type ServerToWorker_GlobalNotification struct {
	GlobalNotification string `protobuf:"bytes,6,opt,name=global_notification,json=globalNotification,proto3,oneof"`
}

func (*ServerToWorker_CreateRouterReq) isServerToWorker_Payload() {}

func (*ServerToWorker_CreateTransportReq) isServerToWorker_Payload() {}

func (*ServerToWorker_ProduceReq) isServerToWorker_Payload() {}

func (*ServerToWorker_ConsumerReq) isServerToWorker_Payload() {}

func (*ServerToWorker_GlobalNotification) isServerToWorker_Payload() {}

var File_singal_proto protoreflect.FileDescriptor

const file_singal_proto_rawDesc = "" +
	"\n" +
	"\fsingal.proto\x12\x06server\"\xe9\x02\n" +
	"\n" +
	"ListenInfo\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12+\n" +
	"\x11announced_address\x18\x04 \x01(\tR\x10announcedAddress\x12!\n" +
	"\fannounced_ip\x18\x05 \x01(\tR\vannouncedIp\x12%\n" +
	"\x0eannounced_port\x18\x06 \x01(\rR\rannouncedPort\x12\x10\n" +
	"\x03tcp\x18\a \x01(\bR\x03tcp\x12\x1a\n" +
	"\bipv6Only\x18\b \x01(\bR\bipv6Only\x12\"\n" +
	"\fudpReusePort\x18\t \x01(\bR\fudpReusePort\x12(\n" +
	"\x10recv_buffer_size\x18\n" +
	" \x01(\rR\x0erecvBufferSize\x12(\n" +
	"\x10send_buffer_size\x18\v \x01(\rR\x0esendBufferSize\"\x8f\x01\n" +
	"\x13CreateRouterRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1a\n" +
	"\bserverId\x18\x03 \x01(\tR\bserverId\x12&\n" +
	"\x04info\x18\x04 \x01(\v2\x12.server.ListenInfoR\x04info\"p\n" +
	"\x14CreateRouterResponse\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\ferror_detail\x18\x03 \x01(\tR\verrorDetail\"E\n" +
	"\x0fDtlsFingerprint\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb9\x01\n" +
	"\fIceCandidate\x12\x1e\n" +
	"\n" +
	"foundation\x18\x01 \x01(\tR\n" +
	"foundation\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\rR\bpriority\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x05 \x01(\rR\x04port\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x19\n" +
	"\btcp_type\x18\a \x01(\tR\atcpType\"\xab\x02\n" +
	"\x16CreateTransportRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\trouter_id\x18\x02 \x01(\tR\brouterId\x12!\n" +
	"\ftransport_id\x18\x03 \x01(\tR\vtransportId\x128\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x1a.server.TransportDirectionR\tdirection\x12\x1d\n" +
	"\n" +
	"enable_udp\x18\x05 \x01(\bR\tenableUdp\x12\x1d\n" +
	"\n" +
	"enable_tcp\x18\x06 \x01(\bR\tenableTcp\x12\x1d\n" +
	"\n" +
	"prefer_udp\x18\a \x01(\bR\tpreferUdp\x12\x1d\n" +
	"\n" +
	"prefer_tcp\x18\b \x01(\bR\tpreferTcp\"\xcf\x02\n" +
	"\x17CreateTransportResponse\x12!\n" +
	"\ftransport_id\x18\x01 \x01(\tR\vtransportId\x12\x1b\n" +
	"\tice_ufrag\x18\x02 \x01(\tR\biceUfrag\x12\x17\n" +
	"\aice_pwd\x18\x03 \x01(\tR\x06icePwd\x12;\n" +
	"\x0eice_candidates\x18\x04 \x03(\v2\x14.server.IceCandidateR\riceCandidates\x12D\n" +
	"\x11dtls_fingerprints\x18\x05 \x03(\v2\x17.server.DtlsFingerprintR\x10dtlsFingerprints\x12\x1b\n" +
	"\tdtls_role\x18\x06 \x01(\tR\bdtlsRole\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12!\n" +
	"\ferror_detail\x18\b \x01(\tR\verrorDetail\"u\n" +
	"\x0eProduceRequest\x12!\n" +
	"\ftransport_id\x18\x01 \x01(\tR\vtransportId\x12%\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x11.server.MediaKindR\x04kind\x12\x19\n" +
	"\bapp_data\x18\x03 \x01(\tR\aappData\"o\n" +
	"\x0fProduceResponse\x12\x1f\n" +
	"\vproducer_id\x18\x01 \x01(\tR\n" +
	"producerId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12!\n" +
	"\ferror_detail\x18\x03 \x01(\tR\verrorDetail\"T\n" +
	"\x0eConsumeRequest\x12!\n" +
	"\ftransport_id\x18\x01 \x01(\tR\vtransportId\x12\x1f\n" +
	"\vproducer_id\x18\x02 \x01(\tR\n" +
	"producerId\"\xb7\x01\n" +
	"\x0fConsumeResponse\x12\x1f\n" +
	"\vconsumer_id\x18\x01 \x01(\tR\n" +
	"consumerId\x12\x1f\n" +
	"\vproducer_id\x18\x02 \x01(\tR\n" +
	"producerId\x12%\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x11.server.MediaKindR\x04kind\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12!\n" +
	"\ferror_detail\x18\x05 \x01(\tR\verrorDetail\"\xee\x02\n" +
	"\x0eWorkerToServer\x12\x15\n" +
	"\x06seq_id\x18\x01 \x01(\x04R\x05seqId\x12J\n" +
	"\x11create_router_res\x18\x02 \x01(\v2\x1c.server.CreateRouterResponseH\x00R\x0fcreateRouterRes\x12S\n" +
	"\x14create_transport_res\x18\x03 \x01(\v2\x1f.server.CreateTransportResponseH\x00R\x12createTransportRes\x12:\n" +
	"\vproduce_res\x18\x04 \x01(\v2\x17.server.ProduceResponseH\x00R\n" +
	"produceRes\x12<\n" +
	"\fconsumer_res\x18\x05 \x01(\v2\x17.server.ConsumeResponseH\x00R\vconsumerRes\x12\x1f\n" +
	"\n" +
	"stats_push\x18\x06 \x01(\tH\x00R\tstatsPushB\t\n" +
	"\apayload\"\xfc\x02\n" +
	"\x0eServerToWorker\x12\x15\n" +
	"\x06seq_id\x18\x01 \x01(\x04R\x05seqId\x12I\n" +
	"\x11create_router_req\x18\x02 \x01(\v2\x1b.server.CreateRouterRequestH\x00R\x0fcreateRouterReq\x12R\n" +
	"\x14create_transport_req\x18\x03 \x01(\v2\x1e.server.CreateTransportRequestH\x00R\x12createTransportReq\x129\n" +
	"\vproduce_req\x18\x04 \x01(\v2\x16.server.ProduceRequestH\x00R\n" +
	"produceReq\x12;\n" +
	"\fconsumer_req\x18\x05 \x01(\v2\x16.server.ConsumeRequestH\x00R\vconsumerReq\x121\n" +
	"\x13global_notification\x18\x06 \x01(\tH\x00R\x12globalNotificationB\t\n" +
	"\apayload*d\n" +
	"\x12TransportDirection\x12\x12\n" +
	"\x0eDIRECTION_AUTO\x10\x00\x12\x12\n" +
	"\x0eDIRECTION_SEND\x10\x01\x12\x12\n" +
	"\x0eDIRECTION_RECV\x10\x02\x12\x12\n" +
	"\x0eDIRECTION_BOTH\x10\x03*7\n" +
	"\tMediaKind\x12\x14\n" +
	"\x10MEDIA_KIND_AUDIO\x10\x00\x12\x14\n" +
	"\x10MEDIA_KIND_VIDEO\x10\x012K\n" +
	"\rWebRtcService\x12:\n" +
	"\x04Sync\x12\x16.server.WorkerToServer\x1a\x16.server.ServerToWorker(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_singal_proto_rawDescOnce sync.Once
	file_singal_proto_rawDescData []byte
)

func file_singal_proto_rawDescGZIP() []byte {
	file_singal_proto_rawDescOnce.Do(func() {
		file_singal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_singal_proto_rawDesc), len(file_singal_proto_rawDesc)))
	})
	return file_singal_proto_rawDescData
}

var file_singal_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_singal_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_singal_proto_goTypes = []any{
	(TransportDirection)(0),         // 0: server.TransportDirection
	(MediaKind)(0),                  // 1: server.MediaKind
	(*ListenInfo)(nil),              // 2: server.ListenInfo
	(*CreateRouterRequest)(nil),     // 3: server.CreateRouterRequest
	(*CreateRouterResponse)(nil),    // 4: server.CreateRouterResponse
	(*DtlsFingerprint)(nil),         // 5: server.DtlsFingerprint
	(*IceCandidate)(nil),            // 6: server.IceCandidate
	(*CreateTransportRequest)(nil),  // 7: server.CreateTransportRequest
	(*CreateTransportResponse)(nil), // 8: server.CreateTransportResponse
	(*ProduceRequest)(nil),          // 9: server.ProduceRequest
	(*ProduceResponse)(nil),         // 10: server.ProduceResponse
	(*ConsumeRequest)(nil),          // 11: server.ConsumeRequest
	(*ConsumeResponse)(nil),         // 12: server.ConsumeResponse
	(*WorkerToServer)(nil),          // 13: server.WorkerToServer
	(*ServerToWorker)(nil),          // 14: server.ServerToWorker
}
var file_singal_proto_depIdxs = []int32{
	2,  // 0: server.CreateRouterRequest.info:type_name -> server.ListenInfo
	0,  // 1: server.CreateTransportRequest.direction:type_name -> server.TransportDirection
	6,  // 2: server.CreateTransportResponse.ice_candidates:type_name -> server.IceCandidate
	5,  // 3: server.CreateTransportResponse.dtls_fingerprints:type_name -> server.DtlsFingerprint
	1,  // 4: server.ProduceRequest.kind:type_name -> server.MediaKind
	1,  // 5: server.ConsumeResponse.kind:type_name -> server.MediaKind
	4,  // 6: server.WorkerToServer.create_router_res:type_name -> server.CreateRouterResponse
	8,  // 7: server.WorkerToServer.create_transport_res:type_name -> server.CreateTransportResponse
	10, // 8: server.WorkerToServer.produce_res:type_name -> server.ProduceResponse
	12, // 9: server.WorkerToServer.consumer_res:type_name -> server.ConsumeResponse
	3,  // 10: server.ServerToWorker.create_router_req:type_name -> server.CreateRouterRequest
	7,  // 11: server.ServerToWorker.create_transport_req:type_name -> server.CreateTransportRequest
	9,  // 12: server.ServerToWorker.produce_req:type_name -> server.ProduceRequest
	11, // 13: server.ServerToWorker.consumer_req:type_name -> server.ConsumeRequest
	13, // 14: server.WebRtcService.Sync:input_type -> server.WorkerToServer
	14, // 15: server.WebRtcService.Sync:output_type -> server.ServerToWorker
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_singal_proto_init() }
func file_singal_proto_init() {
	if File_singal_proto != nil {
		return
	}
	file_singal_proto_msgTypes[11].OneofWrappers = []any{
		(*WorkerToServer_CreateRouterRes)(nil),
		(*WorkerToServer_CreateTransportRes)(nil),
		(*WorkerToServer_ProduceRes)(nil),
		(*WorkerToServer_ConsumerRes)(nil),
		(*WorkerToServer_StatsPush)(nil),
	}
	file_singal_proto_msgTypes[12].OneofWrappers = []any{
		(*ServerToWorker_CreateRouterReq)(nil),
		(*ServerToWorker_CreateTransportReq)(nil),
		(*ServerToWorker_ProduceReq)(nil),
		(*ServerToWorker_ConsumerReq)(nil),
		(*ServerToWorker_GlobalNotification)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_singal_proto_rawDesc), len(file_singal_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_singal_proto_goTypes,
		DependencyIndexes: file_singal_proto_depIdxs,
		EnumInfos:         file_singal_proto_enumTypes,
		MessageInfos:      file_singal_proto_msgTypes,
	}.Build()
	File_singal_proto = out.File
	file_singal_proto_goTypes = nil
	file_singal_proto_depIdxs = nil
}
